### ISSUE TITLE
0.13 tracking issue

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-secp256k1#75]
Breaking changes for 0.12:

- [x] Change serde serialization for human-readable formats to hex encodings
- [x] Upgrade upstream libsecp to one with https://github.com/bitcoin-core/secp256k1/pull/553
- [x] Remove `&Secp256k1` arg from all functions that use a no-caps context, use the static one instead.
- [x] Remove the `key::ZERO` constant since this can be used to trigger assertation failures.
- [x] Change second argument to `add_assign` and `mul_assign` from a `SecretKey` to a `&[u8]`
- [x] Feature-gate recovery module

Nonbreaking changes we should also do:
- [x] Finish implementing `Display` and `FromStr` for all types that do hex-encoding https://github.com/rust-bitcoin/rust-secp256k1/pull/60
- [x] Delete `Secp256k1::without_caps()` which no longer has any use

**Comment by real-or-random** [comment]
>     * [ ]  Make `add_assign` and `mul_assign` actually use the `AddAssign` and `MulAssign` traits; we should also implement `Add` and `Mul` for that matter.
I don't think that works because `add_assign` and `mul_assign` can fail and the trait doesn't support that.

**Comment by apoelstra** [comment]
@real-or-random if we define a trait that describes hash functions (or something), then we can define these those functions for those objects. Then they could only fail with negligible probability and we don't need to worry about it.

**Comment by real-or-random** [comment]
Indeed. But then this is just different functionality, no?

**Comment by apoelstra** [comment]
Yeah. I'll remove it from the tracking list because it's probably a post-0.12 thing to figure that out.

**Comment by sgeisler** [comment]
Can this issue be closed since `0.12.0` was released?

**Comment by apoelstra** [comment]
No, there are still a couple things I want to do

**Comment by vlad9486** [comment]
Second argument to `add_assign` is important for [revocation keys derivation](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#revocationpubkey-derivation) for Lightning. There is no way to convert `SecretKey` into raw bytes, so there is no legitimate (safe) way to perform secret key derivation.

**Comment by TheBlueMatt** [comment]
You should be able to use [..] to get the bytes out of a secret key no problem. See, eg, this line in rust-lightning: https://github.com/rust-bitcoin/rust-lightning/blob/master/src/ln/chan_utils.rs#L80

**Comment by vlad9486** [comment]
Thanks, @TheBlueMatt, I missed this.

**Comment by apoelstra** [comment]
All done :)
